/*global Ember */

var App = window.App = Ember.Application.create({
    LOG_TRANSITIONS: true
});

DS.Store.extend({
    revision: 11,
    //adapter: DS.RESTAdapter.create()
    adapter: DS.LSAdapter.create()
});

App.Router.map(function() {

    // generated by ember-generate --scaffold
    this.resource('bookings');
    this.resource('booking', {path: '/bookings/:booking_id'});
    this.route('edit_booking', {path: '/bookings/:booking_id/edit'});
    this.route('new_booking', {path: '/bookings/new'});
    // end generated routes

});

App.IndexRoute = Ember.Route.extend({
    redirect: function() {
        this.transitionTo('bookings');
    }
});


/* requires processed by neuter */
require('app/scripts/models/*');
require('app/scripts/controllers/*');
require('app/scripts/views/*');


//var BookingRoute = Ember.Route.extend({
//
//    model: function() {
//        return Booking.find();
//    }
//
//});
//
//var NewBookingRoute = Ember.Route.extend({
//
//    renderTemplate: function() {
//        this.render('edit_booking', {controller: 'new_booking'});
//    },
//
//    model: function() {
//        return booking.createRecord();
//    },
//
//    deactivate: function() {
//        var model = this.get('controller.model');
//        if (!model.get('isSaving')) {
//            model.deleteRecord();
//        }
//    }
//
//});